import Head from 'next/head';
import { Inter } from 'next/font/google';

import { computed, signal } from '@preact/signals-react';
import { TSource } from '@/pages/index.d';
import Convert from '@/components/convert';

const inter = Inter({ subsets: ['latin'] });

export const source = signal<TSource>({
  prefix: 'PREFIX',
  url: 'http://',
  raw: '',
});

export const sourceObject = computed(() => source.value);

export default function Home() {
  return (
    <>
      <Head>
        <title>Change log convert</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto p-4 min-w-[1140px] h-[calc(100dvh-68px)]">
        <Convert />
      </main>
    </>
  );
}
